services:
  postgres:
    image: postgres:16-alpine
    container_name: twitter_db
    environment:
      POSTGRES_USER: twitter
      POSTGRES_PASSWORD: twitter
      POSTGRES_DB: twitter
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
